[project]
name = "earthquake-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basemap>=2.0.0",
    "geopandas>=1.1.1",
    "ipykernel>=7.1.0",
    "keras>=3.12.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "scikeras>=0.13.0",
    "scikit-learn>=1.7.2",
    "tensorflow>=2.20.0",
]
